### ISSUE TITLE
这个demo反应太慢了，需要1.06s的响应时间？这个正常吗？还是filter写的有问题？

### ISSUE THREAD

**Issue by ExtremeYu** [jiangmin168168/jim-framework#3]

**Comment by ExtremeYu** [comment]
能不能 回复下啊

**Comment by jiangmin168168** [comment]
抱歉，我一般晚上才会收邮件，你说的时间，1.06是怎么统计的

**Comment by ExtremeYu** [comment]
是真的好慢，跑你的demo，也很慢，浏览器一刷新，要一秒才响应

**Comment by ExtremeYu** [comment]
我意思是，把一个consumer 两个provider跑起来，然后在浏览器测试，发现反应很慢！

**Comment by jiangmin168168** [comment]
性能问题我暂时未做过多测试，周末抽空我测试下

**Comment by jiangmin168168** [comment]
我修改了测试代码，只调用一次远程接口，看起来正常：https://github.com/jiangmin168168/jim-framework/blob/master/jim-framework-doc/images/dubbo-zipkin.jpg
