### ISSUE TITLE
cache这个项目可以用在生产吗？

### ISSUE THREAD

**Issue by kaitezhan** [jiangmin168168/jim-framework#4]
请问下稳定吗？

**Comment by jiangmin168168** [comment]
抱歉，您这个邮件被outlook归到其它目录中，没有及时看到。


这个项目后面更新的版本大部分是从真实项目中开源出来了，未经过大型项目实践，小项目倒是有，您有需要的话可以先拿小项目试试，有问题我们再沟通。


Sent from Outlook<http://aka.ms/weboutlook>


________________________________
