### ISSUE TITLE
zipkin-dubbo可以用dubbo2.6版本么？

### ISSUE THREAD

**Issue by gMan1990** [jiangmin168168/jim-framework#5]
rt

**Comment by jiangmin168168** [comment]
这个没有测试过，当时我做这个测试环境时的dubbo低于你说的这个版本

**Comment by zhaheng** [comment]
@gMan1990 
我的dubbo使用的2.6版本，TraceContext.getTraceConfig()为null，初始化时对象是有值的。不知道是不是dubbo的版本原因

**Comment by jiangmin168168** [comment]
抽时间我测试下，之前没测试过高版本

**Comment by jiangmin168168** [comment]
已经做了测试，在dubbo 2.6.3下是可以使用的
