### ISSUE TITLE
[提议]dubbo zipkin扩展实现进入dubbo生态

### ISSUE THREAD

**Issue by diecui1202** [jiangmin168168/jim-framework#6]
@jiangmin168168 我们是Apache Dubbo(incubating)的社区开发，我们非常希望你的zipkin-dubbo能进入dubbo生态（github.com/dubbo)，未来一起把dubbo社区和生态做大。期待你的答复！

**Comment by jiangmin168168** [comment]
抱歉，看到您的信息已经快一年了，最近一年写文章少，看消息更少。

**Comment by diecui1202** [comment]
没有啊，我是6月份给你发消息的，这块我们可以一起再讨论一下。

**Comment by jiangmin168168** [comment]
喔，我记错了。可以的，静候您的消息。

**Comment by jiangmin168168** [comment]
已经解决
