### ISSUE TITLE
TraceContext.getTraceConfig()为null是什么情况？

### ISSUE THREAD

**Issue by zhaheng** [jiangmin168168/jim-framework#7]
我的环境:springboot2.0+dubbo2.6
项目结构和你的差不多，也是提供者和消费者分别引入com.jim.framework.dubbo.core
启动的时候加载时traceConfig不为null
    @PostConstruct
    public void init() throws Exception {
        TraceContext.init(this.traceConfig);
    }
DEBUG的时候TraceConsumerFilter类的TraceContext.getTraceConfig()获取为null，找不到原因

**Comment by jiangmin168168** [comment]
我抽空测试下2.6的版本，暂时给不出结论，抱歉

**Comment by jiangmin168168** [comment]
你再看下，我这边做测试没有问题，获取下
