### ISSUE TITLE
关于异步调用

### ISSUE THREAD

**Issue by jingb** [jiangmin168168/jim-framework#9]
楼主你们生产的项目，用dubbo的异步调用多么，我们全部都是同步调用
另外dubbo现在支持的异步调用并不完善，还有些坑  比方 A -> B 是异步  B的处理过程里本来是同步调的C，然鹅因为 A调B的时候在context里设置了异步的标志，导致B调C也变成了异步，然后会取不到结果

**Comment by jiangmin168168** [comment]
我们基本没用异步的，也是同步调用，极个别的用那个oneway方式
